### ISSUE TITLE
Audio file longer than value in argument 'file_splitting_duration_s' causes error

### ISSUE THREAD

**Issue by fegue** [birdnet-team/birdnet#2]
When trying to use `model.predict_species_within_audio_file()` with a longer audio file than the value in argument 'file_splitting_duration_s'  (default = 600) causes the following error:

```
Traceback (most recent call last):
  File "example/example.py", line 24, in <module>
    predictions = model.predict_species_within_audio_file(
  File "birdnet/.venv/lib/python3.10/site-packages/birdnet/models/model_v2m4.py", line 401, in predict_species_within_audio_file
    assert (chunk_start, chunk_end) not in predictions
AssertionError
```

Reproduce the error by setting the argument to something less than the example file:
 
```
from pathlib import Path

from birdnet.models import ModelV2M4

# create model instance for v2.4
model = ModelV2M4()

# predict species within the whole audio file
audio_path = Path("example/soundscape.wav")
predictions = model.predict_species_within_audio_file(audio_path, file_splitting_duration_s=60)
```

**Comment by stefantaubert** [comment]
Thanks! I'll have a look at it tomorrow.
